"""
Report Generator Agent - Creates professional DOCX assessment reports
Generates executive-ready documentation for VaultZero 1.0
UPDATED: Compatible with 4-phase roadmap and actual recommendation structure
"""

import os
from datetime import datetime
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

class ReportGeneratorAgent:
    def __init__(self):
        """Initialize the Report Generator Agent"""
        pass
    
    def generate_report(self, 
                       system_description: str,
                       assessment_results: dict,
                       benchmark_results: dict,
                       recommendations: dict,
                       roadmap: dict):
        """Generate comprehensive DOCX report"""
        
        print("\n📄 Generating professional DOCX report...")
        
        doc = Document()
        
        # Add all sections
        self._add_cover_page(doc, assessment_results)
        self._add_executive_summary(doc, assessment_results, benchmark_results, roadmap)
        self._add_assessment_details(doc, assessment_results)
        self._add_benchmark_analysis(doc, benchmark_results)
        self._add_recommendations(doc, recommendations)
        self._add_roadmap(doc, roadmap)
        
        # Save report
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"VaultZero_Assessment_Report_{timestamp}.docx"
        doc.save(filename)
        
        print(f"✅ Report generated: {filename}")
        return filename
    
    def _add_cover_page(self, doc: Document, assessment: dict):
        """Add professional cover page"""
        # Title
        title = doc.add_heading('Zero Trust Security Assessment', level=1)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        for run in title.runs:
            run.font.size = Pt(28)
            run.font.color.rgb = RGBColor(0, 112, 192)
        
        doc.add_paragraph()
        
        # System name
        if 'system_name' in assessment:
            system_para = doc.add_paragraph(assessment['system_name'])
            system_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            for run in system_para.runs:
                run.font.size = Pt(18)
                run.font.bold = True
        
        doc.add_paragraph()
        doc.add_paragraph()
        
        # Date and metadata
        metadata = doc.add_paragraph()
        metadata.alignment = WD_ALIGN_PARAGRAPH.CENTER
        date_str = datetime.now().strftime("%B %d, %Y")
        maturity = assessment.get('overall_maturity_level', 'N/A')
        score = assessment.get('overall_score', 0)
        
        metadata.add_run(f"Assessment Date: {date_str}\n\n")
        metadata.add_run(f"Current Maturity: {maturity}\n")
        metadata.add_run(f"Overall Score: {score:.1f}/4.0\n\n")
        metadata.add_run("Generated by VaultZero Platform")
        
        for run in metadata.runs:
            run.font.size = Pt(12)
        
        doc.add_page_break()
    
    def _add_executive_summary(self, doc: Document, assessment: dict, 
                               benchmark: dict, roadmap: dict):
        """Add executive summary section"""
        doc.add_heading('Executive Summary', level=1)
        
        # Get expected outcomes safely
        expected_outcomes = roadmap.get('expected_outcomes', {})
        total_investment = roadmap.get('total_investment', {})
        
        # Key metrics table
        table = doc.add_table(rows=5, cols=2)
        table.style = 'Light Grid Accent 1'
        
        metrics = [
            ('Current Maturity Level', assessment.get('overall_maturity_level', 'N/A')),
            ('Overall Score', f"{assessment.get('overall_score', 0):.1f}/4.0"),
            ('Peer Ranking', f"{benchmark.get('overall_percentile', 0)}th percentile"),
            ('24-Month Target', expected_outcomes.get('24_month_maturity_target', '4.0/4.0')),
            ('Total Investment', f"{total_investment.get('two_year_total_min', '$700K')} - {total_investment.get('two_year_total_max', '$1.45M')}")
        ]
        
        for i, (label, value) in enumerate(metrics):
            row = table.rows[i]
            row.cells[0].text = label
            row.cells[0].paragraphs[0].runs[0].font.bold = True
            row.cells[1].text = str(value)
        
        doc.add_paragraph()
        
        # Summary text
        summary_text = f"""
This Zero Trust security assessment evaluates your organization's current security posture across five critical pillars. 
Your overall maturity level is {assessment.get('overall_maturity_level', 'N/A')} with a score of {assessment.get('overall_score', 0):.1f}/4.0, 
placing you in the {benchmark.get('overall_percentile', 0)}th percentile compared to peer organizations.

This report provides a comprehensive 2-year transformation roadmap designed to elevate your Zero Trust maturity to 
{expected_outcomes.get('24_month_maturity_target', '4.0/4.0')} level, with an estimated investment of 
{total_investment.get('two_year_total_min', '$700K')} to {total_investment.get('two_year_total_max', '$1.45M')}.
        """
        doc.add_paragraph(summary_text.strip())
        
        doc.add_page_break()
    
    def _add_assessment_details(self, doc: Document, assessment: dict):
        """Add detailed assessment results"""
        doc.add_heading('Detailed Assessment Results', level=1)
        
        doc.add_paragraph('This section provides a pillar-by-pillar analysis of your Zero Trust security posture.')
        doc.add_paragraph()
        
        for pillar_name, pillar_data in assessment.get('pillars', {}).items():
            doc.add_heading(f'{pillar_name.upper()} Security', level=2)
            
            # Metrics
            metrics_para = doc.add_paragraph()
            metrics_para.add_run(f"Maturity Level: {pillar_data.get('maturity_level', 'N/A')}\n").bold = True
            metrics_para.add_run(f"Score: {pillar_data.get('score', 0):.1f}/4.0\n")
            
            # Findings
            if 'findings' in pillar_data:
                doc.add_paragraph('Assessment Findings:', style='Heading 3')
                doc.add_paragraph(pillar_data['findings'])
            
            # Strengths
            if pillar_data.get('strengths'):
                doc.add_paragraph('Strengths:', style='Heading 3')
                for strength in pillar_data['strengths']:
                    p = doc.add_paragraph(strength, style='List Bullet')
                    p.runs[0].font.color.rgb = RGBColor(0, 176, 80)
            
            # Gaps
            if pillar_data.get('gaps'):
                doc.add_paragraph('Areas for Improvement:', style='Heading 3')
                for gap in pillar_data['gaps']:
                    p = doc.add_paragraph(gap, style='List Bullet')
                    p.runs[0].font.color.rgb = RGBColor(192, 0, 0)
            
            doc.add_paragraph()
        
        doc.add_page_break()
    
    def _add_benchmark_analysis(self, doc: Document, benchmark: dict):
        """Add benchmark comparison section"""
        doc.add_heading('Benchmark Analysis', level=1)
        
        doc.add_paragraph(f"Your organization ranks in the {benchmark.get('overall_percentile', 0)}th percentile compared to peer organizations.")
        doc.add_paragraph()
        
        # Competitive position
        if 'competitive_position' in benchmark:
            doc.add_heading('Competitive Position', level=2)
            doc.add_paragraph(benchmark['competitive_position'])
        
        # Pillar rankings
        if 'pillar_rankings' in benchmark:
            doc.add_heading('Pillar-by-Pillar Comparison', level=2)
            
            for pillar, ranking in benchmark['pillar_rankings'].items():
                p = doc.add_paragraph(style='List Bullet')
                p.add_run(f"{pillar.upper()}: ").bold = True
                p.add_run(f"{ranking.get('percentile', 0)}th percentile - {ranking.get('vs_peers', 'N/A')}")
        
        # Strengths vs peers
        if benchmark.get('strengths_vs_peers'):
            doc.add_heading('Your Competitive Advantages', level=2)
            for strength in benchmark['strengths_vs_peers']:
                p = doc.add_paragraph(strength, style='List Bullet')
                p.runs[0].font.color.rgb = RGBColor(0, 176, 80)
        
        # Gaps vs peers
        if benchmark.get('gaps_vs_peers'):
            doc.add_heading('Areas Lagging Behind Peers', level=2)
            for gap in benchmark['gaps_vs_peers']:
                p = doc.add_paragraph(gap, style='List Bullet')
                p.runs[0].font.color.rgb = RGBColor(192, 0, 0)
        
        doc.add_page_break()
    
    def _add_recommendations(self, doc: Document, recommendations: dict):
        """Add recommendations section"""
        doc.add_heading('Prioritized Recommendations', level=1)
        
        doc.add_paragraph('Based on the assessment and benchmark analysis, we recommend the following prioritized initiatives:')
        doc.add_paragraph()
        
        # Critical gaps
        if recommendations.get('critical_gaps'):
            doc.add_heading('Critical Gaps to Address', level=2)
            for gap in recommendations['critical_gaps']:
                doc.add_heading(f"{gap.get('pillar', 'N/A').upper()}: {gap.get('gap', 'N/A')}", level=3)
                # Use risk_level if available, fallback to priority
                risk = gap.get('risk_level', gap.get('priority', 'N/A'))
                doc.add_paragraph(f"Risk Level: {risk}")
                # Use impact_if_not_fixed if available, fallback to business_impact
                impact = gap.get('impact_if_not_fixed', gap.get('business_impact', 'N/A'))
                doc.add_paragraph(f"Impact if Not Fixed: {impact}")
                doc.add_paragraph()
        
        # Top recommendations
        if recommendations.get('prioritized_recommendations'):
            doc.add_heading('Top 10 Priority Initiatives', level=2)
            
            for rec in recommendations['prioritized_recommendations'][:10]:
                # Get rank or priority
                priority = rec.get('rank', rec.get('priority', '?'))
                title = rec.get('title', rec.get('recommendation', 'N/A'))
                
                doc.add_heading(f"Priority #{priority}: {title}", level=3)
                
                details = doc.add_paragraph()
                details.add_run(f"Pillar: {rec.get('pillar', 'N/A').upper()}\n")
                details.add_run(f"Rationale: {rec.get('rationale', 'N/A')}\n")
                # Use expected_impact if available, fallback to impact_score
                expected_impact = rec.get('expected_impact', f"Impact Score: {rec.get('impact_score', 'N/A')}/10")
                details.add_run(f"Expected Impact: {expected_impact}\n")
                # Use effort_estimate, cost_estimate
                effort = rec.get('effort_estimate', rec.get('estimated_effort', 'N/A'))
                cost = rec.get('cost_estimate', 'Cost TBD')
                details.add_run(f"Effort: {effort} | Cost: {cost}\n")
                
                if rec.get('quick_win'):
                    qw_para = doc.add_paragraph('⚡ QUICK WIN - High impact, low effort initiative')
                    qw_para.runs[0].font.color.rgb = RGBColor(255, 140, 0)
                
                doc.add_paragraph()
        
        doc.add_page_break()
    
    def _add_roadmap(self, doc: Document, roadmap: dict):
        """Add 2-year roadmap section with 4-phase support"""
        doc.add_heading('2-Year Implementation Roadmap', level=1)
        
        # Executive summary if available
        if roadmap.get('executive_summary'):
            doc.add_paragraph(roadmap['executive_summary'])
        else:
            doc.add_paragraph("This roadmap provides a phased approach to improving your Zero Trust security posture over 24 months.")
        doc.add_paragraph()
        
        # Investment summary
        doc.add_heading('Total Investment', level=2)
        inv = roadmap.get('total_investment', {})
        
        two_year_total = f"{inv.get('two_year_total_min', '$700K')} - {inv.get('two_year_total_max', '$1.45M')}"
        doc.add_paragraph(f"2-Year Total: {two_year_total}")
        doc.add_paragraph(f"Phase 1 (0-3 months): {inv.get('phase_1', '$50K-$150K')}")
        doc.add_paragraph(f"Phase 2 (3-6 months): {inv.get('phase_2', '$150K-$300K')}")
        doc.add_paragraph(f"Phase 3 (6-12 months): {inv.get('phase_3', '$300K-$600K')}")
        doc.add_paragraph(f"Phase 4 (12-24 months): {inv.get('phase_4', '$200K-$400K')}")
        doc.add_paragraph()
        
        # Handle 4-phase roadmap structure
        phases = roadmap.get('phases', [])
        
        if phases:
            # NEW 4-phase structure
            for phase in phases:
                phase_num = phase.get('phase_number', '?')
                phase_name = phase.get('name', 'Unknown Phase')
                timeframe = phase.get('timeframe', 'TBD')
                
                doc.add_heading(f'Phase {phase_num}: {phase_name} ({timeframe})', level=2)
                doc.add_paragraph(f"Focus: {phase.get('focus', 'N/A')}")
                doc.add_paragraph(f"Target Maturity: {phase.get('maturity_target', 'N/A')}")
                doc.add_paragraph(f"Initiatives: {phase.get('initiatives_count', 0)} key projects")
                doc.add_paragraph()
        
        # Detailed roadmap text from AI
        if roadmap.get('roadmap_text'):
            doc.add_heading('Detailed Implementation Plan', level=2)
            # Add roadmap text in paragraphs (split by newlines)
            roadmap_text = roadmap['roadmap_text']
            for para in roadmap_text.split('\n\n'):
                if para.strip():
                    doc.add_paragraph(para.strip())
        
        doc.add_page_break()
        
        # Expected outcomes
        outcomes = roadmap.get('expected_outcomes', {})
        doc.add_heading('Expected Outcomes (24 Months)', level=2)
        
        doc.add_paragraph(f"Target Maturity: {outcomes.get('24_month_maturity_target', '4.0/4.0')}")
        doc.add_paragraph()
        
        # Maturity improvements
        if outcomes.get('maturity_improvements'):
            doc.add_heading('Maturity Improvements:', level=3)
            for improvement in outcomes['maturity_improvements']:
                doc.add_paragraph(improvement, style='List Bullet')
        
        doc.add_paragraph()
        
        # Compliance achievements
        if outcomes.get('compliance_achievements'):
            doc.add_heading('Compliance Achievements:', level=3)
            for achievement in outcomes['compliance_achievements']:
                doc.add_paragraph(achievement, style='List Bullet')
        
        doc.add_paragraph()
        
        # Security posture improvements
        if outcomes.get('security_posture'):
            doc.add_heading('Security Posture Improvements:', level=3)
            for improvement in outcomes['security_posture']:
                doc.add_paragraph(improvement, style='List Bullet')
        
        doc.add_paragraph()
        
        # Operational benefits
        if outcomes.get('operational_benefits'):
            doc.add_heading('Operational Benefits:', level=3)
            for benefit in outcomes['operational_benefits']:
                doc.add_paragraph(benefit, style='List Bullet')
    
    def run_report_generation(self, system_description: str, assessment_results: dict,
                             benchmark_results: dict, recommendations: dict, roadmap: dict):
        """Complete report generation workflow"""
        print("\n" + "="*70)
        print("📄 VAULTZERO REPORT GENERATOR AGENT")
        print("="*70)
        print("Generating professional DOCX report...")
        
        filename = self.generate_report(system_description, assessment_results, 
                                        benchmark_results, recommendations, roadmap)
        
        print("\n" + "="*70)
        print(f"✅ Professional report generated: {filename}")
        print("="*70)
        
        return filename


if __name__ == "__main__":
    print("Report Generator Agent test - use through orchestrator")
